### PR TITLE
Recaptcha Enterprise Service

### PR DESCRIPTION
**Pull request by maciejziaja**
Would be nice to have recaptcha enterprise service in here too.

### CODE REVIEW

**Review by Enngage — CHANGES_REQUESTED** [review]
Hello! Thank you for the PR!

However, in order for me to merge it, could you please make changes as to not duplicate the logic behind services? Rather, the url of the domain should be configurable and should use identical script service.

**Comment by maciejziaja** [comment]
Hey! Something like that? This would be breaking change if anyone is using `scriptService.registerCaptchaScript` directly in app.

**Comment by lslaz** [comment]
Is this something that will be supported? ngx-recaptcha would be the only recaptcha enterprise solution for angular.

**Comment by krrajiv** [comment]
We are using recaptcha Entreprise, is this something that will be merged into `ng-captcha`

**Review by Enngage — APPROVED** [review]

**Comment by mikaelboff** [comment]
Hi @Enngage , the new version were generated??

**Pull request merged**
